OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg reg_measure[3];
x q[0];
rz(pi/2) q[1];
sx q[1];
rz(pi/2) q[1];
cx q[0],q[1];
rz(pi/2) q[0];
sx q[0];
rz(-pi) q[0];
sx q[1];
rz(pi/2) q[1];
cx q[0],q[1];
rz(-pi/2) q[4];
barrier q[4],q[0],q[1];
measure q[4] -> reg_measure[0];
measure q[0] -> reg_measure[1];
measure q[1] -> reg_measure[2];
