OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
creg reg_measure[3];
rz(-pi/2) q[0];
x q[5];
rz(pi/2) q[6];
sx q[6];
rz(pi/2) q[6];
cx q[5],q[6];
rz(pi/2) q[5];
sx q[5];
rz(-pi) q[5];
sx q[6];
rz(pi/2) q[6];
cx q[5],q[6];
barrier q[0],q[5],q[6];
measure q[0] -> reg_measure[0];
measure q[5] -> reg_measure[1];
measure q[6] -> reg_measure[2];
