OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
creg reg_measure[3];
rz(-pi/2) q[2];
rz(pi/2) q[5];
sx q[5];
rz(pi/2) q[5];
x q[6];
cx q[6],q[5];
sx q[5];
rz(pi/2) q[5];
rz(pi/2) q[6];
sx q[6];
rz(-pi) q[6];
cx q[6],q[5];
barrier q[2],q[6],q[5];
measure q[2] -> reg_measure[0];
measure q[6] -> reg_measure[1];
measure q[5] -> reg_measure[2];
