OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
creg reg_measure[3];
x q[1];
rz(pi/2) q[3];
sx q[3];
rz(pi/2) q[3];
cx q[1],q[3];
rz(pi/2) q[1];
sx q[1];
rz(-pi) q[1];
sx q[3];
rz(pi/2) q[3];
cx q[1],q[3];
rz(-pi/2) q[5];
barrier q[5],q[1],q[3];
measure q[5] -> reg_measure[0];
measure q[1] -> reg_measure[1];
measure q[3] -> reg_measure[2];
