OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
creg reg_measure[3];
rz(-pi/2) q[1];
rz(pi/2) q[4];
sx q[4];
rz(pi/2) q[4];
x q[5];
cx q[5],q[4];
sx q[4];
rz(pi/2) q[4];
rz(pi/2) q[5];
sx q[5];
rz(-pi) q[5];
cx q[5],q[4];
barrier q[1],q[5],q[4];
measure q[1] -> reg_measure[0];
measure q[5] -> reg_measure[1];
measure q[4] -> reg_measure[2];
