OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg reg_measure[3];
rz(-pi/2) q[0];
x q[2];
rz(pi/2) q[3];
sx q[3];
rz(pi/2) q[3];
cx q[2],q[3];
rz(pi/2) q[2];
sx q[2];
rz(-pi) q[2];
sx q[3];
rz(pi/2) q[3];
cx q[2],q[3];
barrier q[0],q[2],q[3];
measure q[0] -> reg_measure[0];
measure q[2] -> reg_measure[1];
measure q[3] -> reg_measure[2];
